### ISSUE TITLE
轮播图左右滑动和SwipeRefreshLayout的下拉刷新的冲突

### ISSUE THREAD

**Issue by NeighborMrYU** [Allure0/LMBanners#3]
轮播图左右滑动时很容易会触发SwipeRefreshLayout的下拉刷新要怎么解决

**Comment by M2dL1fe** [comment]
重写SwipeRefreshLayout 分发事件

**Comment by Allure0** [comment]
继承SwipeRefreshLayout 在onInterceptTouchEvent方法里进行判断，如果是左右滑动自己不处理事件，分发给子控件，如果是上下滑动就拦截事件，自己处理
